### ISSUE TITLE
Lost of namespaces

### ISSUE THREAD

**Issue by zoggy** [aantron/lambdasoup#12]
Is there a reason for throwing away namespace prefixes ?

https://github.com/aantron/lambda-soup/blob/master/src/soup.ml#L122-L124

**Comment by aantron** [comment]
There is no really good reason at this point.

The original reason was that this library was written over Ocamlnet's `Nethtml` parser. As you can see, [its API](http://projects.camlcity.org/projects/dl/ocamlnet-4.1.2/doc/html-main/Nethtml.html) doesn't expose namespaces.

**Comment by aantron** [comment]
Is this something you would like to see added?

**Comment by zoggy** [comment]
Yes, as I got bitten when reading and writing xhtml containing svg: missing namespaces resulted in incorrect svg.

**Comment by aantron** [comment]
Fair enough. I will add them, in I guess some weeks. Thanks for reporting.

**Comment by zoggy** [comment]
Thanks, There is no emergency.

**Comment by aantron** [comment]
I hadn't known about this before: https://www.w3.org/TR/2014/REC-css-namespaces-3-20140320/

**Comment by toastal** [comment]
Any new word on this? I could use the support for SVG parsing right now.
