### ISSUE TITLE
Support escaped selectors and document it

### ISSUE THREAD

**Issue by Chris00** [aantron/lambdasoup#27]
In view of [this issue about selectors containing a colon](https://github.com/ocaml/ocaml.org/issues/1093#issuecomment-552818192), it would be nice to make sure that lambdasoup supports selectors [with escape sequences](https://drafts.csswg.org/css2/syndata.html#value-def-identifier) and to document it (so it is clear to the users).

**Comment by aantron** [comment]
Lambda Soup now supports escape sequences in selector identifiers. In particular, see this new test for escaped colons:

https://github.com/aantron/lambdasoup/blob/b53b69f721fd59beb62b7e7a42eb0943e967d179/test/test.ml#L179

https://github.com/aantron/lambdasoup/blob/b53b69f721fd59beb62b7e7a42eb0943e967d179/test/pages/quoted.html#L17
