### ISSUE TITLE
Publish new verison to pam

### ISSUE THREAD

**Issue by hongchangwu** [aantron/lambdasoup#29]
The latest published version still depends on `jbuilder`. Can you publish a new version that uses `dune`? Thanks.

**Comment by aantron** [comment]
Thanks for the poke. I created [release 0.6.4](https://github.com/aantron/lambdasoup/releases/tag/0.6.4), and the PR for merging it into opam is [here](https://github.com/ocaml/opam-repository/pull/15517).
