### ISSUE TITLE
allow ':' in ids

### ISSUE THREAD

**Issue by mro** [aantron/lambdasoup#59]
currently (v1.0.0) seems not the case:

```utop
utop # {|<a id="fn:uhu">a</a>|} |> Soup.parse |> Soup.select_one "#fn:uhu";;
Exception: Soup.Parse_error "unknown pseudo-class or pseudo-element ':uhu'".
```

but colons are legit in ids, e.g. https://www.w3.org/TR/xhtml-modularization/abstraction.html#dt_ID and https://www.w3.org/TR/xml/#NT-NameChar.

Aren't the pseudos always after double colons?

P.S.: I came across this issue when trying to adopt https://digitalcourage.social/@mro/112891681709585335 in https://mro.name/pagerake

**Comment by mro** [comment]
ah - escape it! https://digitalcourage.social/@mro/112891719464884054

```utop
utop # {|<a id="fn:uhu">a</a>|} |> Soup.parse |> Soup.select_one {|#fn\:uhu|};;
- : Soup.element Soup.node option = Some <abstr>
```

**Comment by aantron** [comment]
The standard that determines selector syntax for Lambda Soup is [CSS Selectors](https://www.w3.org/TR/selectors-3/). Per section [*ID selectors*](https://www.w3.org/TR/selectors-3/#id-selectors),

> An ID selector contains a "number sign" (U+0023, #) immediately followed by the ID value, which must be an CSS [identifiers](https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier).

Following the link to the definition of an *identifier*,

> In CSS, *identifiers* (including element names, classes, and IDs in [selectors](https://www.w3.org/TR/CSS21/selector.html)) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit. Identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item).

So yes, the colon needs to be escaped to be written as part of an ID selector. Perhaps the message could be improved to be less misleading.
