### ISSUE TITLE
Can you cut a new release?

### ISSUE THREAD

**Issue by justbhoot** [aantron/lambdasoup#60]
I want to create a PR to [soupault](https://github.com/PataphysicalSociety/soupault) in order to upgrade it `lambdasoup` dependency, so that `:has()` selector becomes usable there.

Let me know if I can help.

cc @dmbaturin

**Comment by aantron** [comment]
The release is in progress here: https://github.com/ocaml/opam-repository/pull/26388.

**Comment by justbhoot** [comment]
Released on opam. Thank you!
